services:
  - type: web
    name: pdf-tools-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7  # Use uma versão completa aqui
